export const CARTDECREASE = "CARTDECREASE";
export const CARTINCREASE = "CARTINCREASE";
export const CARTREMOVE = "CARTREMOVE";
export const CLEAR_CART = "CLEAR_CART";
export const GET_TOTALS = "GET_TOTALS";
export const TOGGLE_AMOUNT = "TOGGLE_AMOUNT";
